x-base_service: &backend
  build: .
  depends_on:
    - db
    - redis
  env_file:
    - .env
  environment:
    - PYTHONUNBUFFERED=1

services:
  flask:
    <<: *backend
    command: /bin/sh -c "python utils/wait_for_postgres.py && alembic upgrade head && flask run --debug --host=0.0.0.0 --port=5003"
    ports:
      - "5003:5003"
    volumes:
      - .:/app  # Mount the current directory to /app in the container

  celery_worker:
    <<: *backend
    command: /bin/sh -c "python utils/wait_for_postgres.py && celery -A app.celery worker --loglevel=info -c 2"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
