volumes:
  db_data:

x-base_service: &backend
  build: .
  depends_on:
    - db
    - redis
  env_file:
    - .env
  environment:
    - PYTHONUNBUFFERED=1
  volumes:
    - .:/app

services:
  flask:
    <<: *backend
    command: /bin/sh -c "alembic upgrade head && flask run --debug --host=0.0.0.0 --port=5003"
    ports:
      - "5003:5003"

  celery_worker:
    <<: *backend
    command: watchmedo auto-restart --pattern "*.py" --recursive -- celery -A app.celery worker -l info -c 2

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: "postgres:alpine"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
