"""add relationship to audio log for events/thoughts

Revision ID: 08812979068d
Revises: 67dbb819b08e
Create Date: 2024-02-27 14:34:41.398968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08812979068d'
down_revision: Union[str, None] = '67dbb819b08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('note', sa.Text(), nullable=True))
    op.drop_column('events', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('events', 'note')
    # ### end Alembic commands ###
