"""change transcription -> audio logs

Revision ID: 2487e1a316b3
Revises: 8a5bd979af23
Create Date: 2024-02-27 13:17:40.749419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2487e1a316b3'
down_revision: Union[str, None] = '8a5bd979af23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assemblyai_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('identified_things', sa.JSON(), nullable=True),
    sa.Column('raw_events', sa.JSON(), nullable=True),
    sa.Column('raw_thoughts', sa.JSON(), nullable=True),
    sa.Column('raw_shallow_analysis', sa.JSON(), nullable=True),
    sa.Column('raw_deep_analysis', sa.JSON(), nullable=True),
    sa.Column('system_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transcriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assemblyai_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shallow_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deep_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transcriptions_pkey')
    )
    op.drop_table('audio_logs')
    # ### end Alembic commands ###
