"""add default value to system notes

Revision ID: 3c1ce5ca1f75
Revises: 2487e1a316b3
Create Date: 2024-02-27 13:33:56.448665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1ce5ca1f75'
down_revision: Union[str, None] = '2487e1a316b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
