"""add relationship to audio log for events/thoughts

Revision ID: 67dbb819b08e
Revises: e3049ab4dc8b
Create Date: 2024-02-27 14:26:33.159897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67dbb819b08e'
down_revision: Union[str, None] = 'e3049ab4dc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
