"""add fields to transcriptions

Revision ID: 8a5bd979af23
Revises: a502419d035a
Create Date: 2024-02-21 18:10:26.000565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5bd979af23'
down_revision: Union[str, None] = 'a502419d035a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('shallow_analysis', sa.JSON(), nullable=True))
    op.add_column('transcriptions', sa.Column('deep_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'deep_analysis')
    op.drop_column('transcriptions', 'shallow_analysis')
    # ### end Alembic commands ###
