"""add relationship to audio log for events/thoughts

Revision ID: 8f0b938b3954
Revises: 3c1ce5ca1f75
Create Date: 2024-02-27 14:06:25.386493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0b938b3954'
down_revision: Union[str, None] = '3c1ce5ca1f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('audio_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'audio_logs', ['audio_log_id'], ['id'])
    op.add_column('thoughts', sa.Column('audio_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thoughts', 'audio_logs', ['audio_log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thoughts', type_='foreignkey')
    op.drop_column('thoughts', 'audio_log_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'audio_log_id')
    # ### end Alembic commands ###
