"""add assemblyai id

Revision ID: a502419d035a
Revises: 7a38afa13400
Create Date: 2024-02-21 15:05:14.596112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a502419d035a'
down_revision: Union[str, None] = '7a38afa13400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('assemblyai_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'assemblyai_id')
    # ### end Alembic commands ###
