"""add relationship to audio log for events/thoughts

Revision ID: c6e1025096d7
Revises: 08812979068d
Create Date: 2024-02-27 14:36:20.958057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e1025096d7'
down_revision: Union[str, None] = '08812979068d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'raw_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
