"""add relationship to audio log for events/thoughts

Revision ID: d65577133ba8
Revises: c6e1025096d7
Create Date: 2024-02-27 14:41:16.827087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65577133ba8'
down_revision: Union[str, None] = 'c6e1025096d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('thoughts_text_key', 'thoughts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('thoughts_text_key', 'thoughts', ['text'])
    # ### end Alembic commands ###
