"""add relationship to audio log for events/thoughts

Revision ID: e3049ab4dc8b
Revises: 8f0b938b3954
Create Date: 2024-02-27 14:25:56.654787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3049ab4dc8b'
down_revision: Union[str, None] = '8f0b938b3954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
